ARG BASE_IMAGE=0.2.2
ARG ALIAS=biop/

ARG CELLPOSE_VERSION=3.1.1.1
ARG QUPATH_VERSION=v0.5.1-04
ARG FIJI_VERSION=20250319
ARG SAMAPI_VERSION=0.6.1

FROM ${ALIAS}biop-samapi:${SAMAPI_VERSION} AS samapi-image
FROM ${ALIAS}biop-qupath:${QUPATH_VERSION} AS qupath-image
FROM ${ALIAS}biop-cellpose:${CELLPOSE_VERSION} AS cellpose-image
FROM ${ALIAS}biop-fiji:${FIJI_VERSION} AS fiji-image
FROM ${ALIAS}biop-vnc-base:${BASE_IMAGE}

ENV PATH=$PATH:/opt/conda/bin 

USER root

################################################
# # Install QuPath 
COPY --from=qupath-image /opt/QuPath /opt/QuPath
COPY --from=qupath-image /home/biop/Desktop/QuPath.desktop  /home/biop/Desktop/QuPath.desktop

#################################################################
# Install Fiji
COPY --from=fiji-image /opt/Fiji.app /opt/Fiji.app
COPY fiji/Fiji_setWrappersPaths.groovy /home/biop/tmp/Fiji_setWrappersPaths.groovy

##################################################################
# Install cellpose and models
COPY --from=cellpose-image  /opt/conda/envs/cellpose /opt/conda/envs/cellpose
COPY --from=cellpose-image /home/biop/.cellpose/models/ /home/biop/.cellpose/models/

#################################################################
# Install samapi
#
# add lib for wsl 
ENV LD_LIBRARY_PATH=/usr/lib/wsl/lib:$LD_LIBRARY_PATH
# add samapi env 
COPY --from=samapi-image /opt/conda/envs/samapi /opt/conda/envs/samapi
# add models for samapi
COPY --from=samapi-image /home/biop/.samapi/ /home/biop/.samapi/

######################################################################
USER biop 
#install VScode extensions
RUN yes | code --install-extension ms-python.python
RUN yes | code --install-extension ms-toolsai.jupyter 
USER root

# #################################################################
# # Jupyter kernels 
# #install pix2pix envrionment + add a kernel
COPY gan4mic/env_pix2pix.yml /tmp/env_pix2pix.yml
RUN conda env create -n pix2pix -f /tmp/env_pix2pix.yml \
    && rm /tmp/env_pix2pix.yml 

RUN source activate cellpose \
     && python -m pip install ipykernel \
     && conda deactivate

# # To make the different conda env available in jupyter
COPY jupyter/kernels/ /home/biop/.local/share/jupyter/kernels/
#remove other kernels 
RUN rm -r -f /home/biop/.local/share/jupyter/kernels/brainrender \
    && rm -r -f /home/biop/.local/share/jupyter/kernels/devbio \
    && rm -r -f /home/biop/.local/share/jupyter/kernels/empanada \
    && rm -r -f /home/biop/.local/share/jupyter/kernels/omnipose 
    
# # Make icons on desktop
COPY icons/* /opt/icons/
# # to start fiji
RUN printf '[Desktop Entry]\nVersion=1.0\nName=ImageJ\nGenericName=ImageJ\nX-GNOME-FullName=ImageJ\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/Fiji.app/ImageJ-linux64 %F\nTryExec=/opt/Fiji.app/ImageJ-linux64\nTerminal=false\nStartupNotify=true\nMimeType=image/*;\nIcon=/opt/Fiji.app/images/icon.png\nStartupWMClass=net-imagej-launcher-ClassLauncher\n' > /home/biop/Desktop/Fiji.desktop \
# # to start QuPath
    && printf '[Desktop Entry]\nVersion=0.5.1\nName=qupath\nGenericName=QuPath\nX-GNOME-FullName=QuPath\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/QuPath/bin/QuPath\nTryExec=/opt/QuPath/bin/QuPath\nTerminal=false\nStartupNotify=true\nIcon=/opt/QuPath/lib/QuPath.png\nStartupWMClass=QuPath' > /home/biop/Desktop/QuPath.desktop \
# # to start SAMAPI
    && printf 'source activate samapi\npython -m uvicorn samapi.main:app --workers 2\n\$ read -rsp \$"Press enter to continue..."' > /opt/icons/start_samapi.sh \
    && printf '[Desktop Entry]\nVersion=0.6.1\nName=samapi\nGenericName=samapi\nX-GNOME-FullName=samapi\nComment=Scientific Image Analysis\nType=Application\nCategories=Education;Science;ImageProcessing;\nExec=/opt/icons/start_samapi.sh\nTryExec=/opt/icons/start_samapi.sh\nTerminal=true\nStartupNotify=true\nIcon=/opt/icons/samapi.ico\nStartupWMClass=samapi\n' > /home/biop/Desktop/samapi.desktop \
# # set permissions
    && chown -R biop:biop   /home/biop/             /opt/icons/ \
    && chmod -R a+rwx       /home/biop/Desktop/     /opt/icons/ \
#  # waiting for RunAI patch
    && ln -s /usr/lib/x86_64-linux-gnu/libcuda.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so

# ##################################################################
# # Prepare to set QP_prefs 
COPY QuPath/prefs/QuPath_setPaths.groovy /home/biop/tmp/QuPath_setPaths.groovy
COPY QuPath/prefs/qp_prefs.xml /home/biop/tmp/qp_prefs.xml
RUN chown -R biop:biop /home/biop/tmp

###################################################################
# #permissions
# # set chown and chmod for all necessary folders
RUN chown -R biop:biop /opt/QuPath/QuPath_Common_Data_0.5 \
    && chmod -R a+rwx /opt/QuPath/QuPath_Common_Data_0.5 \
    && chmod a+rwx /opt/QuPath/bin/QuPath \
    && chmod -R a+rwx /home/biop/.cellpose \
    && chown -R biop:biop /home/biop/.samapi/ \
    && chmod -R a+rwx /home/biop/.samapi/ \
    && chown biop:biop /opt/Fiji.app/ \
    && chmod -R a+rwx /opt/Fiji.app/ 

#################################################################
# Container start
USER biop
RUN /opt/QuPath/bin/QuPath script '/home/biop/tmp/QuPath_setPaths.groovy' \
     && /opt/Fiji.app/ImageJ-linux64 --headless --run /home/biop/tmp/Fiji_setWrappersPaths.groovy \
     && rm -rf /home/biop/tmp
WORKDIR /home/biop
ENTRYPOINT ["/usr/local/bin/jupyter"]
CMD ["lab", "--allow-root", "--ip=*", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.allow_origin='*'", "--notebook-dir=/home/biop"]
